export const CommercialVesselTypes = [
    { key: 'cargo', label: 'Cargo Vessel' },
    { key: 'container', label: 'Container Ship' },
    { key: 'bulk-carrier', label: 'Bulk Carrier' },
    { key: 'tanker', label: 'Tanker' },
    { key: 'passenger', label: 'Passenger Vessel' },
    { key: 'ferry', label: 'Ferry' },
    { key: 'ro-ro', label: 'Ro-Ro Vessel' },
    { key: 'fishing', label: 'Fishing Vessel' },
    { key: 'trawler', label: 'Fishing Trawler' },
    { key: 'tug', label: 'Tugboat' },
    { key: 'workboat', label: 'Workboat' },
    { key: 'offshore', label: 'Offshore Support Vessel' },
    { key: 'research', label: 'Research Vessel' },
    { key: 'dredger', label: 'Dredger' },
    { key: 'workboat', label: 'Workboat' },
    { key: 'crew-boat', label: 'Crew Boat' },
    { key: 'pilot-boat', label: 'Pilot Boat' },
    { key: 'supply-vessel', label: 'Offshore Supply Vessel (OSV)' },
    { key: 'platform-supply', label: 'Platform Supply Vessel (PSV)' },
    { key: 'anchor-handling', label: 'Anchor Handling Tug (AHT)' },
    { key: 'tugboat', label: 'Tugboat' },
    { key: 'push-boat', label: 'Push Boat' },
    { key: 'barge', label: 'Barge' },
    { key: 'dredger', label: 'Dredger' },
    { key: 'passenger-vessel', label: 'Passenger Vessel' },
    { key: 'landing-craft', label: 'Landing Craft' },
    { key: 'patrol-boat', label: 'Patrol Boat' },
    { key: 'rescue-vessel', label: 'Rescue Vessel' },
    { key: 'fireboat', label: 'Fireboat' },
    { key: 'survey-vessel', label: 'Survey Vessel' },
    { key: 'research-vessel', label: 'Research Vessel' },
    { key: 'cable-layer', label: 'Cable Layer' },
    { key: 'pipe-layer', label: 'Pipe Layer' },
    { key: 'heavy-lift', label: 'Heavy Lift Vessel' },
    { key: 'other', label: 'Other Commercial Vessel' }
];