  export const PowerVesselTypes = [
    { key: "power-aft-cabin", label: "Aft Cabin" },
    { key: "power-airboat", label: "Airboat" },
    { key: "power-aluminium-fish", label: "Aluminium Fish" },
    { key: "power-antique-and-classic", label: "Antique and Classic" },
    { key: "power-barge", label: "Barge" },
    { key: "power-bass", label: "Bass" },
    { key: "power-bay", label: "Bay" },
    { key: "power-bowrider", label: "Bowrider" },
    { key: "power-canal-and-river-cruiser", label: "Canal and River Cruiser" },
    { key: "power-center-console", label: "Center Console" },
    { key: "power-commercial", label: "Commercial" },
    { key: "power-convertible", label: "Convertible" },
    { key: "power-cruise-ships", label: "Cruise ships" },
    { key: "power-cruiser", label: "Cruiser" },
    { key: "power-cuddy-cabin", label: "Cuddy Cabin" },
    { key: "power-deck", label: "Deck" },
    { key: "power-dinghy", label: "Dinghy" },
    { key: "power-dive", label: "Dive" },
    { key: "power-downeast", label: "Downeast" },
    { key: "power-dual-console", label: "Dual Console" },
    { key: "power-express-cruiser", label: "Express Cruiser" },
    { key: "power-flats", label: "Flats" },
    { key: "power-flybridge", label: "Flybridge" },
    { key: "power-freshwater-fishing", label: "Freshwater Fishing" },
    { key: "power-gulet", label: "Gulet" },
    { key: "power-high-performance", label: "High Performance" },
    { key: "power-house", label: "House" },
    { key: "power-inflatable", label: "Inflatable" },
    { key: "power-jet", label: "Jet" },
    { key: "power-jon", label: "Jon" },
    { key: "power-llaut", label: "Llaut" },
    { key: "power-lobster", label: "Lobster" },
    { key: "power-mega-yacht", label: "Mega Yacht" },
    { key: "power-motor-yachts", label: "Motor Yachts" },
    { key: "power-motorsailer", label: "Motorsailer" },
    { key: "power-narrow", label: "Narrow" },
    { key: "power-other", label: "Other" },
    { key: "power-passenger", label: "Passenger" },
    { key: "power-personal-watercraft", label: "Personal Watercraft" },
    { key: "power-pilothouse", label: "Pilothouse" },
    { key: "power-pontoon", label: "Pontoon" },
    { key: "power-power-catamaran", label: "Power Catamaran" },
    { key: "power-rigid-inflatable-boats-(rib)", label: "Rigid Inflatable Boats (RIB)" },
    { key: "power-runabout", label: "Runabout" },
    { key: "power-saltwater-fishing", label: "Saltwater Fishing" },
    { key: "power-ski-and-fish", label: "Ski and Fish" },
    { key: "power-ski-and-wakeboard", label: "Ski and Wakeboard" },
    { key: "power-skiff", label: "Skiff" },
    { key: "power-sport-fishing", label: "Sport Fishing" },
    { key: "power-sports-cruiser", label: "Sports Cruiser" },
    { key: "power-tender", label: "Tender" },
    { key: "power-trawler", label: "Trawler" },
    { key: "power-troller", label: "Troller" },
    { key: "power-tug", label: "Tug" },
    { key: "power-unspecified", label: "Unspecified" },
    { key: "power-utility", label: "Utility" },
    { key: "power-walkaround", label: "Walkaround" }
  ];