  export const PowerBoatTypes = [
    { slug: "power-aft-cabin", name: "Aft Cabin" },
    { slug: "power-airboat", name: "Airboat" },
    { slug: "power-aluminium-fish", name: "Aluminium Fish" },
    { slug: "power-antique-and-classic", name: "Antique and Classic" },
    { slug: "power-barge", name: "Barge" },
    { slug: "power-bass", name: "Bass" },
    { slug: "power-bay", name: "Bay" },
    { slug: "power-bowrider", name: "Bowrider" },
    { slug: "power-canal-and-river-cruiser", name: "Canal and River Cruiser" },
    { slug: "power-center-console", name: "Center Console" },
    { slug: "power-commercial", name: "Commercial" },
    { slug: "power-convertible", name: "Convertible" },
    { slug: "power-cruise-ships", name: "Cruise ships" },
    { slug: "power-cruiser", name: "Cruiser" },
    { slug: "power-cuddy-cabin", name: "Cuddy Cabin" },
    { slug: "power-deck", name: "Deck" },
    { slug: "power-dinghy", name: "Dinghy" },
    { slug: "power-dive", name: "Dive" },
    { slug: "power-downeast", name: "Downeast" },
    { slug: "power-dual-console", name: "Dual Console" },
    { slug: "power-express-cruiser", name: "Express Cruiser" },
    { slug: "power-flats", name: "Flats" },
    { slug: "power-flybridge", name: "Flybridge" },
    { slug: "power-freshwater-fishing", name: "Freshwater Fishing" },
    { slug: "power-gulet", name: "Gulet" },
    { slug: "power-high-performance", name: "High Performance" },
    { slug: "power-house", name: "House" },
    { slug: "power-inflatable", name: "Inflatable" },
    { slug: "power-jet", name: "Jet" },
    { slug: "power-jon", name: "Jon" },
    { slug: "power-llaut", name: "Llaut" },
    { slug: "power-lobster", name: "Lobster" },
    { slug: "power-mega-yacht", name: "Mega Yacht" },
    { slug: "power-motor-yachts", name: "Motor Yachts" },
    { slug: "power-motorsailer", name: "Motorsailer" },
    { slug: "power-narrow", name: "Narrow" },
    { slug: "power-other", name: "Other" },
    { slug: "power-passenger", name: "Passenger" },
    { slug: "power-personal-watercraft", name: "Personal Watercraft" },
    { slug: "power-pilothouse", name: "Pilothouse" },
    { slug: "power-pontoon", name: "Pontoon" },
    { slug: "power-power-catamaran", name: "Power Catamaran" },
    { slug: "power-rigid-inflatable-boats-(rib)", name: "Rigid Inflatable Boats (RIB)" },
    { slug: "power-runabout", name: "Runabout" },
    { slug: "power-saltwater-fishing", name: "Saltwater Fishing" },
    { slug: "power-ski-and-fish", name: "Ski and Fish" },
    { slug: "power-ski-and-wakeboard", name: "Ski and Wakeboard" },
    { slug: "power-skiff", name: "Skiff" },
    { slug: "power-sport-fishing", name: "Sport Fishing" },
    { slug: "power-sports-cruiser", name: "Sports Cruiser" },
    { slug: "power-tender", name: "Tender" },
    { slug: "power-trawler", name: "Trawler" },
    { slug: "power-troller", name: "Troller" },
    { slug: "power-tug", name: "Tug" },
    { slug: "power-unspecified", name: "Unspecified" },
    { slug: "power-utility", name: "Utility" },
    { slug: "power-walkaround", name: "Walkaround" }
  ];