export const SailBoatTypes = [
    { slug: "sail-antique-and-classic", name: "Antique and Classic" },
    { slug: "sail-beach-catamaran", name: "Beach Catamaran" },
    { slug: "sail-catamaran", name: "Catamaran" },
    { slug: "sail-centre-cockpit", name: "Centre Cockpit" },
    { slug: "sail-commercial", name: "Commercial" },
    { slug: "sail-cruiser", name: "Cruiser" },
    { slug: "sail-cutter", name: "Cutter" },
    { slug: "sail-daysailer", name: "Daysailer" },
    { slug: "sail-deck-saloon", name: "Deck Saloon" },
    { slug: "sail-dinghy", name: "Dinghy" },
    { slug: "sail-gulet", name: "Gulet" },
    { slug: "sail-ketch", name: "Ketch" },
    { slug: "sail-motorsailer", name: "Motorsailer" },
    { slug: "sail-multi-hull", name: "Multi-Hull" },
    { slug: "sail-other", name: "Other" },
    { slug: "sail-performance-sailboats", name: "Performance sailboats" },
    { slug: "sail-pilothouse", name: "Pilothouse" },
    { slug: "sail-racer", name: "Racer" },
    { slug: "sail-racer/cruiser", name: "Racer/Cruiser" },
    { slug: "sail-schooner", name: "Schooner" },
    { slug: "sail-sloop", name: "Sloop" },
    { slug: "sail-trimaran", name: "Trimaran" },
    { slug: "sail-unspecified", name: "Unspecified" },
    { slug: "sail-yawl", name: "Yawl" }
  ];