export const SailVesselTypes = [
    { key: "sail-antique-and-classic", label: "Antique and Classic" },
    { key: "sail-beach-catamaran", label: "Beach Catamaran" },
    { key: "sail-catamaran", label: "Catamaran" },
    { key: "sail-centre-cockpit", label: "Centre Cockpit" },
    { key: "sail-commercial", label: "Commercial" },
    { key: "sail-cruiser", label: "Cruiser" },
    { key: "sail-cutter", label: "Cutter" },
    { key: "sail-daysailer", label: "Daysailer" },
    { key: "sail-deck-saloon", label: "Deck Saloon" },
    { key: "sail-dinghy", label: "Dinghy" },
    { key: "sail-gulet", label: "Gulet" },
    { key: "sail-ketch", label: "Ketch" },
    { key: "sail-motorsailer", label: "Motorsailer" },
    { key: "sail-multi-hull", label: "Multi-Hull" },
    { key: "sail-other", label: "Other" },
    { key: "sail-performance-sailboats", label: "Performance sailboats" },
    { key: "sail-pilothouse", label: "Pilothouse" },
    { key: "sail-racer", label: "Racer" },
    { key: "sail-racer/cruiser", label: "Racer/Cruiser" },
    { key: "sail-schooner", label: "Schooner" },
    { key: "sail-sloop", label: "Sloop" },
    { key: "sail-trimaran", label: "Trimaran" },
    { key: "sail-unspecified", label: "Unspecified" },
    { key: "sail-yawl", label: "Yawl" }
  ];