export enum ListingStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  SUSPENDED = 'SUSPENDED',
  ARCHIVED = 'ARCHIVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED'
}